local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<C-n>', ':Neotree filesystem reveal left<CR>')
vim.api.nvim_set_keymap('i', '<C-e>', "emmet#expandAbbrIntelligent('<C-e>')", { noremap = true, silent = true, expr = true })
